app:
  secret: SEC2167dc252d45f4e05d6e0f337e32101f349fd69272563ea781d55372e5140392
  webhook: https://oapi.dingtalk.com/robot/send?access_token=17925dfa078afdca36a68a50daef9a8585686a9de481707c658815ad6b7edbf6
  host: test.visionagent.cn
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.111.113.232:3306/app?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: dxl
    password: dxl@2020
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    view:
      prefix: /
      suffix: .html
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: 9999